# Generated by Django 4.0 on 2021-12-17 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_verifed',
            new_name='is_verified',
        ),
    ]
